name: Node.js CI/CD Ecommerce

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # THÀNH PHẦN QUAN TRỌNG: Không xóa các file không thuộc git (như node_modules) khi pull code mới
          clean: false

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install dependencies
        run: |
          # Giờ đây lệnh này sẽ chạy siêu nhanh vì cấu trúc node_modules cũ vẫn còn nguyên
          npm install --include=dev --no-audit --no-fund

      - name: Check nodemon version (Optional)
        run: npx nodemon --version || echo "Nodemon is ready"

      - name: Restart server
        run: pm2 restart ecommerce-backend
