name: Node.js CI/CD Ecommerce

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          # KHÔNG dùng tham số cache: 'npm' ở đây để tránh làm nghẽn ổ đĩa EC2

      - name: Install dependencies
        run: |
          # Dùng npm install thay vì npm ci để tận dụng node_modules có sẵn, giảm tải I/O cho EC2
          npm install --include=dev

      - name: Check nodemon version (Optional)
        run: npx nodemon --version || echo "Nodemon is ready"
